### ISSUE TITLE
Default look and feel isn't all it could be

### ISSUE THREAD

**Issue by zeitchef** [dense-analysis/neural#33]
For some reason, the prompt for me looks terrible (border, no icon, color) but I was unable to find anything in the documentation regarding highlight groups.

<img width="1381" alt="Screenshot 2023-03-22 at 21 32 07" src="https://user-images.githubusercontent.com/6670659/227031430-d389c999-0bd4-411a-8a71-353205fd17a4.png">

I'm using a perfectly working Nerd Font. Would appreciate some info on how to change these features.

**Comment by w0rp** [comment]
Let us know the values of the font options you're using, what version of Vim, what character encoding, and anything else you can share.

**Comment by zeitchef** [comment]
@w0rp 

NVIM v0.10.0-dev-415+g55f6a1cab-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
Terminal Emulator: Kitty
Encoding: utf-8

This is my config:

```
return {
	'dense-analysis/neural',
	dependencies = {
		'MunifTanjim/nui.nvim',
		'elpiloto/significant.nvim',
	},
	keys = {
		{ '<leader>N', ':Neural<CR>', desc = 'Prompt neural' },
		{ '<C-a>', '<cmd>Neural<CR>', mode = 'i', desc = 'Prompt neural' },
	},
	config = function()
		require('neural').setup({
			source = {
				openai = {
					api_key = vim.env.OPENAI_API_KEY,
				},
				ui = {
					hl_color = { fg = macchiato.orange, bg = macchiato.base },
					prompt_border_color = { fg = macchiato.orange, bg = macchiato.base },
				},
			},
		})
	end,
}

```

**Comment by w0rp** [comment]
@zeitchef Are you able to share the name of the font you're using and how it's configured for you editor? Maybe if we can load the same font we'll be able to see the same issue with the missing glyph. In any case, have a look at `:help g:neural.ui.prompt_icon`. You can update that setting to whatever character is printable with the font you're using instead of the default lightning bolt.

The `nui` settings for the prompt aren't configurable through our configuration, but if you open up `lua/neural/ui.lua` wherever Neural is installed you can play around with the UI settings. I see it uses a `NeuralPromptBorder` highlight group by the looks of it, which may need documenting. If there are some other settings we could write into the configuration options and apply there, let us know, or submit a PR to add them. The border style is probably a good one to try editing.

**Comment by zeitchef** [comment]
@w0rp I'm using JetBrainsMono Nerd Font. I'll play around with some of these undocumented highlights to see if I can make it work.

**Comment by Angelchev** [comment]
@zeitchef I have made some updates to default highlights and documentation at #46. I have also tested it with kitty terminal using the `JetBrainsMono Nerd Font` and things look as they should:

## Screenshot
![Screenshot_20240103_223726](https://github.com/dense-analysis/neural/assets/38880939/3379e05d-bff9-45be-a7b2-5cbaf4d08598)

Let me know if any issues surface once #46 is merged.
